[package]
name = "enum_tag_lib"
version = "0.1.0"
authors = ["pearisgreen <gerrit.proessl@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.15.33", features = ["full"] }
quote = "0.6"

[lib]
proc-macro = true
